/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trades` | `/trades`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/trade/new`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-4`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-5`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-6`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trades` | `/trades`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/new`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/step-2`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/step-3`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/step-4`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/step-5`; params?: Router.UnknownOutputParams; } | { pathname: `/trade/step-6`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add${`?${string}` | `#${string}` | ''}` | `/add${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trades${`?${string}` | `#${string}` | ''}` | `/trades${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/step-2${`?${string}` | `#${string}` | ''}` | `/onboarding/step-3${`?${string}` | `#${string}` | ''}` | `/trade/new${`?${string}` | `#${string}` | ''}` | `/trade/step-2${`?${string}` | `#${string}` | ''}` | `/trade/step-3${`?${string}` | `#${string}` | ''}` | `/trade/step-4${`?${string}` | `#${string}` | ''}` | `/trade/step-5${`?${string}` | `#${string}` | ''}` | `/trade/step-6${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trades` | `/trades`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/trade/new`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-3`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-4`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-5`; params?: Router.UnknownInputParams; } | { pathname: `/trade/step-6`; params?: Router.UnknownInputParams; };
    }
  }
}
